### ISSUE TITLE
Undefined symbol cef_string_destroy with Valac 0.48

### ISSUE THREAD

**Issue by yochananmarqos** [tiliado/valacef#18]
I tried building on Manjaro GNOME with Spotify's CEF minimal 76.1.13+gf19c584+chromium-76.0.3809.132 release installed.

I used:

```
./waf configure \
	--prefix=/usr \
	--libdir=/usr/lib
make run
```

[Build log](https://pastebin.com/Kx7nnGhN)

**Comment by fenryxo** [comment]
Hello @yochananmarqos.
 
Your linking command is `['/usr/sbin/gcc', '-Wl,--no-undefined', '-Wl,--as-needed', '-shared', 'valacef_api.c.2.o', 'cef.c.2.o', 'version.c.2.o', 'constants.c.2.o', 'Checks.c.2.o', 'V8.c.2.o', 'SimpleInterceptor.c.2.o', 'SimpleAccessor.c.2.o', '-o/home/yochanan/Documents/pkgbuilds/valacef-git/src/valacef/build/libvalacef.so', '-Wl,-rpath,/usr/lib/cef', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/usr/lib/cef', '-lcef', '-lgobject-2.0', '-lglib-2.0', '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now']`.

Mine is: `['/usr/bin/gcc', '-Wl,--no-undefined', '-Wl,--as-needed', '-shared', 'valacef_api.c.2.o', 'cef.c.2.o', 'version.c.2.o', 'constants.c.2.o', 'Checks.c.2.o', 'V8.c.2.o', 'SimpleInterceptor.c.2.o', 'SimpleAccessor.c.2.o', '-o/home/fenryxo/dev/projects/valacef/build/libvalacef.so', '-Wl,-rpath,/app/lib/cef', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/app/lib/cef', '-lcef', '-lgobject-2.0', '-lglib-2.0']`

Try removing `-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now`.

**Comment by yochananmarqos** [comment]
That didn't help, unfortunately.

[Build log](https://pastebin.com/4LjJCEqy)

**Comment by fenryxo** [comment]
Could you attach `src/valacef/build/V8.c` and all `*.vapi` files from your build?

**Comment by yochananmarqos** [comment]
Here you are:
[Link](https://drive.google.com/file/d/153eGCzbQdJYzGhBGs-RGuMIKXiiAquPq/view?usp=sharing)

**Comment by yochananmarqos** [comment]
Did the files give you any clues?

**Comment by fenryxo** [comment]
Valac 0.48 seems to add `cef_string_destroy` calls but it's an undefined symbol. You might try to use older Valac (0.45.2 works fine)

**Comment by yochananmarqos** [comment]
Arch never used 0.45.X, they went from 0.44.7 > 0.46.0 (see [archive](https://archive.archlinux.org/packages/v/vala/)). I tried 0.44.7, 0.46.0 and 0.46.6 to no avail.

**Comment by fenryxo** [comment]
Is the build error always the same?

**Comment by yochananmarqos** [comment]
I don't believe it was exactly the same, but I gave up once I saw no recent versions of `vala` were going to work. The point is this project will never work on rolling release distros like Arch and distros based on it. I was hoping to maintain the AUR packages, however it seems like this will be a fruitless effort. You've lost a potential paying customer as well.

**Comment by fenryxo** [comment]
Nuvola is not in very good shape since I started working fulltime in May 2019. Less time, less love :-( Since I'm the only developer, I'm afraid Nuvola will never be enough actively maintained for rolling distros such as Arch Linux. However, Arch Linux users can install flatpak builds of Nuvola.

Anyway, I hope to upgrade Vala soon (tiliado/nuvolaruntime#603), but I think it's better not to package Valacef and wait for the QtWebEngine port of Nuvola (tiliado/nuvolaruntime#583) instead.

**Comment by fenryxo** [comment]
Fixed in branch 75.3770.x

**Comment by yochananmarqos** [comment]
I tried that branch, the build still fails. I'll wait until you upgrade `vala`.

**Comment by fenryxo** [comment]
All Nuvola flatpaks are now built with Vala 0.48.5.

**Comment by yochananmarqos** [comment]
I tried building with Vala 0.48.5 and Spotify's CEF Minimal 75.1.14+gc81164e+chromium-75.0.3770.100 installed:

```
	./waf distclean configure \
		--prefix=/usr \
		--libdir=/usr/lib
	./waf build -v -p
```

[Build log](https://pastebin.com/mxsmy2dX)

**Comment by fenryxo** [comment]
You need [a patched CEF](https://github.com/tiliado/cef/tree/3770-valacef). I should have mentioned that somewhere in docs (#20).
